version: "3"
services:
  web:
    image: python
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: