version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: friendlyhello
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: